/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DemoImport } from './routes/demo'
import { Route as IndexImport } from './routes/index'
import { Route as AuthorIndexImport } from './routes/author/index'
import { Route as AuthorNamespaceImport } from './routes/author/$namespace'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorIndexRoute = AuthorIndexImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorNamespaceRoute = AuthorNamespaceImport.update({
  id: '/author/$namespace',
  path: '/author/$namespace',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/author/$namespace': {
      id: '/author/$namespace'
      path: '/author/$namespace'
      fullPath: '/author/$namespace'
      preLoaderRoute: typeof AuthorNamespaceImport
      parentRoute: typeof rootRoute
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginLazyRoute
  '/author/$namespace': typeof AuthorNamespaceRoute
  '/author': typeof AuthorIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginLazyRoute
  '/author/$namespace': typeof AuthorNamespaceRoute
  '/author': typeof AuthorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginLazyRoute
  '/author/$namespace': typeof AuthorNamespaceRoute
  '/author/': typeof AuthorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/login' | '/author/$namespace' | '/author'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/login' | '/author/$namespace' | '/author'
  id: '__root__' | '/' | '/demo' | '/login' | '/author/$namespace' | '/author/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  LoginLazyRoute: typeof LoginLazyRoute
  AuthorNamespaceRoute: typeof AuthorNamespaceRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  LoginLazyRoute: LoginLazyRoute,
  AuthorNamespaceRoute: AuthorNamespaceRoute,
  AuthorIndexRoute: AuthorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo",
        "/login",
        "/author/$namespace",
        "/author/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/author/$namespace": {
      "filePath": "author/$namespace.tsx"
    },
    "/author/": {
      "filePath": "author/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
